spring:
  application:
    name: reminder

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml