spring:
  application:
    name: reminder

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#springdoc:
#  api-docs:
#    path: /api-docs.html
#    enabled: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  api:
    url: 'https://api.telegram.org/bot'
    command: '/sendMessage'

scheduling:
  interval: 60000