logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
spring:
  application:
    name: reminder
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  docker:
    compose:
      enabled: true

  datasource:
    url: jdbc:postgresql://database-reminder:5432/reminder
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.yaml

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs.yaml
  swagger-ui:
    url: /openapi.yaml
    try-it-out-enabled: false

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
  api:
    url: 'https://api.telegram.org/bot'
    command: '/sendMessage'

scheduling:
  interval: 180000