spring:
  application:
    name: reminder

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/reminder
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: false